[workspace]
members = ["contracts"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
starknet = "2.7.0"
stark_vrf = { git = "https://github.com/dojoengine/stark-vrf.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.26.0" }
# Scripts are not supported for virtual workspaces.
