[package]
name = "vrf_contracts"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
stark_vrf.workspace = true
openzeppelin.workspace = true
snforge_std.workspace = true

[dev-dependencies]
openzeppelin_testing = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"

[lib]

[script]
test = "snforge test"
